# Generated by Django 4.1.3 on 2024-05-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_author_book_registration',
            name='number_of_pages',
            field=models.IntegerField(),
        ),
    ]
