# Generated by Django 4.1.3 on 2024-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_books_author_book_registration_number_of_pages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books_author_book_registration',
            name='number_of_pages',
        ),
        migrations.AddField(
            model_name='books_author_book_registration',
            name='pageno',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
